import re

WHITELIST_RULES = [
    {
        "brand": "Nike",
        "model": "Alphafly",
        "pattern": re.compile(r"\b(?:air\s*zoom\s*)?alphafly(?:\s*next%?)?(?:\s*[234])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:tempo|rep|first\s*copy|fake|slide|sandal|pegasus)\b", re.IGNORECASE),
    },
    {
        "brand": "Nike",
        "model": "Vaporfly",
        "pattern": re.compile(r"\b(?:zoomx\s*)?vaporfly(?:\s*next%?)?(?:\s*[234])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:flyknit\s*streak|tempo|rep|first\s*copy|fake)\b", re.IGNORECASE),
    },
    {
        "brand": "Nike",
        "model": "Ultrafly",
        "pattern": re.compile(r"\b(?:zoomx\s*)?ultrafly(?:\s*trail)?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:pegasus|wildhorse|kiger|rep|fake)\b", re.IGNORECASE),
    },
    {
        "brand": "Nike",
        "model": "Zoom Fly",
        "pattern": re.compile(r"\bzoom\s*fly(?:\s*[3456])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:tempo|alphafly|vaporfly|streakfly|rep|fake)\b", re.IGNORECASE),
    },
    {
        "brand": "Nike",
        "model": "Streakfly",
        "pattern": re.compile(r"\b(?:zoomx\s*)?streakfly\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:vaporfly|alphafly|tempo|rep|fake)\b", re.IGNORECASE),
    },
    {
        "brand": "Nike",
        "model": "Invincible Run",
        "pattern": re.compile(r"\b(?:zoomx\s*)?invincible(?:\s*run)?(?:\s*flyknit)?(?:\s*[23])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:rep|first\s*copy|fake|slide)\b", re.IGNORECASE),
    },
    {
        "brand": "Nike",
        "model": "Vomero",
        "pattern": re.compile(r"\b(?:air\s*zoom\s*)?vomero(?:\s*(?:16|17|18))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:vomero\s*5\b|premium\s*lifestyle|rep|fake)\b", re.IGNORECASE),
    },
    {
        "brand": "Nike",
        "model": "Pegasus",
        "pattern": re.compile(r"\b(?:air\s*zoom\s*)?pegasus(?:\s*(?:3[89]|4[012]))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:trail|turbo|flyease|easyon|shield|plus|revolution|downshifter|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Nike",
        "model": "Structure",
        "pattern": re.compile(r"\b(?:air\s*zoom\s*)?structure(?:\s*(?:24|25|26))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:triax|rep|fake)\b", re.IGNORECASE),
    },
    {
        "brand": "Adidas",
        "model": "Adizero Adios Pro",
        "pattern": re.compile(r"\b(?:adizero\s+)?adios\s+pro(?:\s*[234])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:evo\s*1|takumi|sen|sl|rc|boston|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Adidas",
        "model": "Adizero Prime X Strung",
        "pattern": re.compile(r"\b(?:adizero\s+)?prime\s*x(?:\s*[23])?(?:\s*strung)?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:primeblue|primegreen|rep|fake)\b", re.IGNORECASE),
    },
    {
        "brand": "Adidas",
        "model": "Adizero Takumi Sen",
        "pattern": re.compile(r"\b(?:adizero\s+)?takumi\s*sen(?:\s*(?:8|9|10))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:adios|pro|sl|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Adidas",
        "model": "Adizero Boston",
        "pattern": re.compile(r"\b(?:adizero\s+)?boston(?:\s*(?:10|11|12))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:celtics|track|pants|jacket|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Adidas",
        "model": "Adizero Adios",
        "pattern": re.compile(r"\b(?:adizero\s+)?adios(?:\s*[789])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:pro|prime|rc|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Adidas",
        "model": "Ultraboost Light",
        "pattern": re.compile(r"\bultraboost\s*(?:light|23|5)\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:dna|1\.0|2\.0|clima|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Adidas",
        "model": "Supernova Prima",
        "pattern": re.compile(r"\bsupernova\s+prima\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:rise|stride|solution|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Adidas",
        "model": "Adizero SL",
        "pattern": re.compile(r"\b(?:adizero\s+)?sl(?:\s*2)?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:sl\s*72|sl\s*20|pro|boston|adios|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Adidas",
        "model": "Supernova Rise",
        "pattern": re.compile(r"\bsupernova\s+rise\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:prima|stride|solution|cushion|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Asics",
        "model": "Metaspeed Sky",
        "pattern": re.compile(r"\bmetaspeed\s+sky(?:\s*\+)?(?:\s*paris)?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:edge|ray|rep|fake)\b", re.IGNORECASE),
    },
    {
        "brand": "Asics",
        "model": "Metaspeed Edge",
        "pattern": re.compile(r"\bmetaspeed\s+edge(?:\s*\+)?(?:\s*paris)?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:sky|ray|rep|fake)\b", re.IGNORECASE),
    },
    {
        "brand": "Asics",
        "model": "Superblast",
        "pattern": re.compile(r"\bsuperblast(?:\s*[123])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:novablast|dynablast|megablast|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Asics",
        "model": "Magic Speed",
        "pattern": re.compile(r"\bmagic\s*speed(?:\s*[234])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:hyper\s*speed|metaspeed|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Asics",
        "model": "Gel-Nimbus",
        "pattern": re.compile(r"\b(?:gel[\s-]*)?nimbus(?:\s*(?:24|25|26|27))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:9|10\.1|lifestyle|rep|fake)\b", re.IGNORECASE),
    },
    {
        "brand": "Asics",
        "model": "Gel-Kayano",
        "pattern": re.compile(r"\b(?:gel[\s-]*)?kayano(?:\s*(?:29|30|31|32))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:14|legacy|lifestyle|rep|fake)\b", re.IGNORECASE),
    },
    {
        "brand": "Asics",
        "model": "Novablast",
        "pattern": re.compile(r"\bnovablast(?:\s*[2345])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:superblast|dynablast|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Asics",
        "model": "Gel-Cumulus",
        "pattern": re.compile(r"\b(?:gel[\s-]*)?cumulus(?:\s*(?:24|25|26|27))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:pulse|contend|excite|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Asics",
        "model": "GT-2000",
        "pattern": re.compile(r"\bgt[\s-]*2000(?:\s*(?:11|12|13))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:gt[\s-]*1000|gt[\s-]*2160|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Puma",
        "model": "Fast-R Nitro Elite",
        "pattern": re.compile(r"\bfast[\s-]*r\s+(?:nitro\s+)?elite(?:\s*[12])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:fast[\s-]*fwd|rep|fake)\b", re.IGNORECASE),
    },
    {
        "brand": "Puma",
        "model": "Deviate Nitro Elite",
        "pattern": re.compile(r"\bdeviate\s+nitro\s+elite(?:\s*[23])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:non-elite|regular|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Puma",
        "model": "Fast-FWD Nitro Elite",
        "pattern": re.compile(r"\bfast[\s-]*fwd\s+(?:nitro\s+)?elite\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:fast[\s-]*r|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Puma",
        "model": "Deviate Nitro",
        "pattern": re.compile(r"\bdeviate\s+nitro(?:\s*[23])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\belite\b", re.IGNORECASE),
    },
    {
        "brand": "Puma",
        "model": "MagMax Nitro",
        "pattern": re.compile(r"\bmagmax\s+nitro\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:magnify|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Puma",
        "model": "ForeverRun Nitro",
        "pattern": re.compile(r"\bforever[\s-]*run\s+nitro(?:\s*[12])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:electrify|velocity|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Puma",
        "model": "Magnify Nitro",
        "pattern": re.compile(r"\bmagnify\s+nitro(?:\s*[12])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:magmax|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Puma",
        "model": "Velocity Nitro",
        "pattern": re.compile(r"\bvelocity\s+nitro(?:\s*[23])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:deviate|liberate|electrify|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Puma",
        "model": "Liberate Nitro",
        "pattern": re.compile(r"\bliberate\s+nitro(?:\s*[12])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:velocity|deviate|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Saucony",
        "model": "Endorphin Elite",
        "pattern": re.compile(r"\bendorphin\s+elite(?:\s*[12])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:pro|speed|shift|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Saucony",
        "model": "Endorphin Pro",
        "pattern": re.compile(r"\bendorphin\s+pro(?:\s*[234])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:elite|speed|shift|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Saucony",
        "model": "Endorphin Speed",
        "pattern": re.compile(r"\bendorphin\s+speed(?:\s*[234])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:pro|elite|shift|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Saucony",
        "model": "Kinvara Pro",
        "pattern": re.compile(r"\bkinvara\s+pro\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:standard|regular|kinvara\s*(?:13|14|15))\b", re.IGNORECASE),
    },
    {
        "brand": "Saucony",
        "model": "Triumph",
        "pattern": re.compile(r"\btriumph(?:\s*(?:20|21|22))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:iso|rfh|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Saucony",
        "model": "Hurricane",
        "pattern": re.compile(r"\bhurricane(?:\s*24)?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:iso|vintage|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Saucony",
        "model": "Tempus",
        "pattern": re.compile(r"\btempus(?:\s*[12])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:guide|omni|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Saucony",
        "model": "Guide",
        "pattern": re.compile(r"\bguide(?:\s*(?:15|16|17))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:iso|ride|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Saucony",
        "model": "Ride",
        "pattern": re.compile(r"\bride(?:\s*(?:15|16|17))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:iso|millennium|rfg|guide|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Saucony",
        "model": "Kinvara",
        "pattern": re.compile(r"\bkinvara(?:\s*(?:13|14|15))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\bpro\b", re.IGNORECASE),
    },
    {
        "brand": "Hoka",
        "model": "Rocket X",
        "pattern": re.compile(r"\brocket\s*x(?:\s*2)?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:cielo|carbon|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Hoka",
        "model": "Cielo X1",
        "pattern": re.compile(r"\bcielo\s*x(?:1)?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:road|track\s*spike|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Hoka",
        "model": "Mach X",
        "pattern": re.compile(r"\bmach\s*x(?:\s*2)?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:mach\s*[56]\b|supersonic)\b", re.IGNORECASE),
    },
    {
        "brand": "Hoka",
        "model": "Carbon X",
        "pattern": re.compile(r"\bcarbon\s*x(?:\s*[23])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:rocket|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Hoka",
        "model": "Bondi",
        "pattern": re.compile(r"\bbondi(?:\s*[789])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:bondi\s*x|sr|leather|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Hoka",
        "model": "Skyward X",
        "pattern": re.compile(r"\bskyward\s*x\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:skyline|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Hoka",
        "model": "Gaviota",
        "pattern": re.compile(r"\bgaviota(?:\s*[45])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:leather|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Hoka",
        "model": "Clifton",
        "pattern": re.compile(r"\bclifton(?:\s*(?:8|9|10))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:clifton\s*l|suede|gore-tex|gtx|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Hoka",
        "model": "Mach",
        "pattern": re.compile(r"\bmach(?:\s*[56])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\bmach\s*x\b", re.IGNORECASE),
    },
    {
        "brand": "Brooks",
        "model": "Hyperion Elite",
        "pattern": re.compile(r"\bhyperion\s+elite(?:\s*[234])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:max|tempo|gts|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Brooks",
        "model": "Hyperion Max",
        "pattern": re.compile(r"\bhyperion\s+max(?:\s*[12])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\belite\b", re.IGNORECASE),
    },
    {
        "brand": "Brooks",
        "model": "Hyperion",
        "pattern": re.compile(r"\bhyperion(?:\s*tempo)?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:elite|max|gts)\b", re.IGNORECASE),
    },
    {
        "brand": "Brooks",
        "model": "Glycerin",
        "pattern": re.compile(r"\bglycerin(?:\s*(?:20|21))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:gts|stealthfit|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Brooks",
        "model": "Glycerin GTS",
        "pattern": re.compile(r"\bglycerin\s+gts(?:\s*(?:20|21))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\bstealthfit\b", re.IGNORECASE),
    },
    {
        "brand": "Brooks",
        "model": "Ghost Max",
        "pattern": re.compile(r"\bghost\s+max(?:\s*[12])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:gtx|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Brooks",
        "model": "Ghost",
        "pattern": re.compile(r"\bghost(?:\s*(?:14|15|16))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:max|gtx|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Brooks",
        "model": "Adrenaline GTS",
        "pattern": re.compile(r"\badrenaline\s+gts(?:\s*(?:22|23|24))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:walker|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Brooks",
        "model": "Launch",
        "pattern": re.compile(r"\blaunch(?:\s*(?:9|10))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\bgts\b", re.IGNORECASE),
    },
    {
        "brand": "New Balance",
        "model": "FuelCell SuperComp Elite",
        "pattern": re.compile(r"\b(?:fuelcell\s+)?(?:sc|supercomp)\s+elite(?:\s*v[34])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:trainer|pacer|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "New Balance",
        "model": "FuelCell SuperComp Trainer",
        "pattern": re.compile(r"\b(?:fuelcell\s+)?(?:sc|supercomp)\s+trainer(?:\s*v[23])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:elite|pacer|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "New Balance",
        "model": "FuelCell SuperComp Pacer",
        "pattern": re.compile(r"\b(?:fuelcell\s+)?(?:sc|supercomp)\s+pacer(?:\s*v[12])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:elite|trainer|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "New Balance",
        "model": "Fresh Foam X 1080",
        "pattern": re.compile(r"\b(?:fresh\s*foam\s*x?\s*)?1080(?:\s*v(?:12|13|14))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:rep|fake)\b", re.IGNORECASE),
    },
    {
        "brand": "New Balance",
        "model": "Fresh Foam X More",
        "pattern": re.compile(r"\b(?:fresh\s*foam\s*x?\s*)?more(?:\s*v[45])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:trail|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "New Balance",
        "model": "Fresh Foam X Vongo",
        "pattern": re.compile(r"\b(?:fresh\s*foam\s*x?\s*)?vongo(?:\s*v[56])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:rep|fake)\b", re.IGNORECASE),
    },
    {
        "brand": "New Balance",
        "model": "FuelCell Rebel",
        "pattern": re.compile(r"\b(?:fuelcell\s+)?rebel(?:\s*v[34])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:propel|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "New Balance",
        "model": "Fresh Foam X 880",
        "pattern": re.compile(r"\b(?:fresh\s*foam\s*x?\s*)?880(?:\s*v(?:13|14))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:gtx|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "New Balance",
        "model": "FuelCell Propel",
        "pattern": re.compile(r"\b(?:fuelcell\s+)?propel(?:\s*v[45])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:rebel|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Skechers",
        "model": "Go Run Speed Beast",
        "pattern": re.compile(r"\b(?:go\s*run\s+)?speed\s+beast\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:walk|d'lites|arch\s*fit\s*(?!go\s*run)|bobs|uno)\b", re.IGNORECASE),
    },
    {
        "brand": "Skechers",
        "model": "Go Run Speed Elite Hyper",
        "pattern": re.compile(r"\b(?:go\s*run\s+)?speed\s+elite(?:\s*hyper)?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:beast|walk|d'lites|uno)\b", re.IGNORECASE),
    },
    {
        "brand": "Skechers",
        "model": "Go Run Razor",
        "pattern": re.compile(r"\b(?:go\s*run\s+)?razor(?:\s*[34])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:excess|trail|walk|d'lites|uno)\b", re.IGNORECASE),
    },
    {
        "brand": "Skechers",
        "model": "Go Run Razor Excess",
        "pattern": re.compile(r"\b(?:go\s*run\s+)?razor\s+excess(?:\s*[12])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:walk|d'lites|uno)\b", re.IGNORECASE),
    },
    {
        "brand": "Skechers",
        "model": "Go Run Max Road",
        "pattern": re.compile(r"\b(?:go\s*run\s+)?max\s*road(?:\s*[56])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:walk|d'lites|uno|glide)\b", re.IGNORECASE),
    },
    {
        "brand": "Skechers",
        "model": "Go Run Ride",
        "pattern": re.compile(r"\b(?:go\s*run\s+)?ride(?:\s*(?:10|11))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:walk|d'lites|uno|pure)\b", re.IGNORECASE),
    },
    {
        "brand": "Skechers",
        "model": "Go Run Pure",
        "pattern": re.compile(r"\b(?:go\s*run\s+)?pure(?:\s*[34])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:ride|razor|walk|d'lites)\b", re.IGNORECASE),
    },
    {
        "brand": "Skechers",
        "model": "Go Run Persistence",
        "pattern": re.compile(r"\b(?:go\s*run\s+)?persistence(?:\s*[12])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:walk|d'lites|uno)\b", re.IGNORECASE),
    },
    {
        "brand": "Skechers",
        "model": "Go Run Consistent",
        "pattern": re.compile(r"\b(?:go\s*run\s+)?consistent(?:\s*2\.0)?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:walk|d'lites|uno)\b", re.IGNORECASE),
    },
    {
        "brand": "On Running",
        "model": "On Cloudboom Echo",
        "pattern": re.compile(r"\bcloudboom\s+echo(?:\s*[23])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:strike|cloudtilt|cloudnova|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "On Running",
        "model": "On Cloudboom Strike",
        "pattern": re.compile(r"\bcloudboom\s+strike\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:echo|cloudnova|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "On Running",
        "model": "On Cloudsurfer Next",
        "pattern": re.compile(r"\bcloudsurfer\s+next\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:trail|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "On Running",
        "model": "On Cloudflow",
        "pattern": re.compile(r"\bcloudflow(?:\s*[34])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:cloudsurfer|cloudflyer|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "On Running",
        "model": "On Cloudmonster",
        "pattern": re.compile(r"\bcloudmonster(?:\s*[12])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:hyper|void|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "On Running",
        "model": "On Cloudmonster Hyper",
        "pattern": re.compile(r"\bcloudmonster\s+hyper\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:void|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "On Running",
        "model": "On Cloudstratus",
        "pattern": re.compile(r"\bcloudstratus(?:\s*[23])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:cloudmonster|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "On Running",
        "model": "On Cloudsurfer",
        "pattern": re.compile(r"\bcloudsurfer(?:\s*(?:6|7))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:next|trail|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "On Running",
        "model": "On Cloudrunner",
        "pattern": re.compile(r"\bcloudrunner(?:\s*[12])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:waterproof|rep)\b", re.IGNORECASE),
    },
    {
        "brand": "Reebok",
        "model": "Floatride Energy X",
        "pattern": re.compile(r"\bfloatride\s+energy\s+x\b", re.IGNORECASE),
        "exclusions": None,
    },
    {
        "brand": "Reebok",
        "model": "Floatride Energy Symmetros",
        "pattern": re.compile(r"\bfloatride\s+energy\s+symmetros(?:\s+[23])?\b", re.IGNORECASE),
        "exclusions": None,
        "category": "running",
    },
    {
        "brand": "Reebok",
        "model": "Floatride Energy",
        "pattern": re.compile(r"\bfloatride\s+energy(?:\s+(?:3|4|5|6))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:energen|x|symmetros|daily)\b", re.IGNORECASE),
        "category": "running",
    },
]

# Curated Top Sneaker, Retro Runner & Heritage Lifestyle Icons
SNEAKER_RULES = [
    # --- Adidas Originals ---
    {
        "brand": "Adidas",
        "model": "SL 72",
        "pattern": re.compile(r"\b(?:adidas\s+originals\s+)?sl\s*72(?:\s*(?:rs|og))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Adidas",
        "model": "Samba",
        "pattern": re.compile(r"\bsamba(?:\s*(?:og|classic|deco|decon|vegan))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:samba\s*golf|first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Adidas",
        "model": "Gazelle",
        "pattern": re.compile(r"\bgazelle(?:\s*(?:indoor|bold|og|85))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Adidas",
        "model": "Handball Spezial",
        "pattern": re.compile(r"\b(?:handball\s+)?spezial\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Adidas",
        "model": "Stan Smith",
        "pattern": re.compile(r"\bstan\s+smith\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Adidas",
        "model": "Superstar",
        "pattern": re.compile(r"\bsuperstar(?:\s*(?:82|adv|xlg))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Adidas",
        "model": "Campus 00s",
        "pattern": re.compile(r"\bcampus(?:\s*(?:00s|80s))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Adidas",
        "model": "Forum Low",
        "pattern": re.compile(r"\bforum(?:\s*(?:low|84|mid|mod))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },

    # --- Nike Sportswear & Heritage ---
    {
        "brand": "Nike",
        "model": "P-6000",
        "pattern": re.compile(r"\bp[-\s]?6000\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Nike",
        "model": "Dunk Low",
        "pattern": re.compile(r"\bdunk(?:\s*(?:low|high|retro|se))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:slam\s*dunk|first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Nike",
        "model": "Air Force 1 '07",
        "pattern": re.compile(r"\b(?:air\s*force\s*1|af1)(?:\s*(?:'07|07|low|shadow|lv8))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Nike",
        "model": "Cortez",
        "pattern": re.compile(r"\bcortez\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Nike",
        "model": "Killshot 2",
        "pattern": re.compile(r"\bkillshot(?:\s*2)?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Nike",
        "model": "Vomero 5",
        "pattern": re.compile(r"\bvomero\s*5\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Nike",
        "model": "Air Max 1",
        "pattern": re.compile(r"\bair\s*max\s*1(?:\s*(?:'86|86|sc|se))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Nike",
        "model": "Air Max 90",
        "pattern": re.compile(r"\bair\s*max\s*90(?:\s*(?:futura|gtx|se|ltr))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Nike",
        "model": "V2K Run",
        "pattern": re.compile(r"\bv2k\s*run\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Nike",
        "model": "Initiator",
        "pattern": re.compile(r"\binitiator\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },

    # --- Asics Sportstyle ---
    {
        "brand": "Asics",
        "model": "Gel-1130",
        "pattern": re.compile(r"\bgel[-\s]?1130\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Asics",
        "model": "Gel-Kayano 14",
        "pattern": re.compile(r"\bgel[-\s]?kayano\s*14\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Asics",
        "model": "Gel-NYC",
        "pattern": re.compile(r"\bgel[-\s]?nyc\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Asics",
        "model": "GT-2160",
        "pattern": re.compile(r"\bgt[-\s]?2160\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Asics",
        "model": "Japan S",
        "pattern": re.compile(r"\bjapan\s*s\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Asics",
        "model": "EX89",
        "pattern": re.compile(r"\bex89\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },

    # --- Puma Sportstyle ---
    {
        "brand": "Puma",
        "model": "Palermo",
        "pattern": re.compile(r"\bpalermo(?:\s*(?:leather|special|og|modena))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Puma",
        "model": "Suede Classic",
        "pattern": re.compile(r"\bsuede\s*(?:classic|xl|vtg|crepe)?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Puma",
        "model": "Clyde",
        "pattern": re.compile(r"\bclyde(?:\s*(?:og|all-pro|core))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Puma",
        "model": "Army Trainer",
        "pattern": re.compile(r"\barmy\s*trainer\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "Puma",
        "model": "Easy Rider",
        "pattern": re.compile(r"\beasy\s*rider\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },

    # --- New Balance Heritage ---
    {
        "brand": "New Balance",
        "model": "New Balance 550",
        "pattern": re.compile(r"\b(?:new\s*balance\s*)?550\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "New Balance",
        "model": "New Balance 574",
        "pattern": re.compile(r"\b(?:new\s*balance\s*)?574(?:\s*(?:core|legacy|rugged))?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "New Balance",
        "model": "New Balance 1906R",
        "pattern": re.compile(r"\b(?:new\s*balance\s*)?1906[rdu]?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "New Balance",
        "model": "New Balance 2002R",
        "pattern": re.compile(r"\b(?:new\s*balance\s*)?2002[rd]?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "New Balance",
        "model": "New Balance 530",
        "pattern": re.compile(r"\b(?:new\s*balance\s*)?530\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "New Balance",
        "model": "New Balance 327",
        "pattern": re.compile(r"\b(?:new\s*balance\s*)?327\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "New Balance",
        "model": "New Balance 9060",
        "pattern": re.compile(r"\b(?:new\s*balance\s*)?9060\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
    {
        "brand": "New Balance",
        "model": "New Balance 990",
        "pattern": re.compile(r"\b(?:new\s*balance\s*)?990(?:\s*v[3456])?\b", re.IGNORECASE),
        "exclusions": re.compile(r"\b(?:first\s*copy|fake|rep)\b", re.IGNORECASE),
        "category": "sneaker",
    },
]

# Ensure category="running" default on existing performance running rules
for _rule in WHITELIST_RULES:
    _rule.setdefault("category", "running")

# Append sneaker rules to the combined whitelist
WHITELIST_RULES.extend(SNEAKER_RULES)

# Set of canonical sneaker models for fast category lookup
SNEAKER_MODEL_NAMES = {r["model"] for r in SNEAKER_RULES}

STEAL_THRESHOLDS = {
    "Alphafly": {'mrp': 22795, 'street': 20495, 'steal': 13499, 'atl': 9995},
    "Vaporfly": {'mrp': 20695, 'street': 17595, 'steal': 11999, 'atl': 8499},
    "Ultrafly": {'mrp': 21995, 'street': 18495, 'steal': 12499, 'atl': 8999},
    "Zoom Fly": {'mrp': 14995, 'street': 11995, 'steal': 7499, 'atl': 4999},
    "Streakfly": {'mrp': 14995, 'street': 10995, 'steal': 6999, 'atl': 4499},
    "Invincible Run": {'mrp': 16995, 'street': 13595, 'steal': 8499, 'atl': 5999},
    "Vomero": {'mrp': 13995, 'street': 10495, 'steal': 6999, 'atl': 4799},
    "Pegasus": {'mrp': 11995, 'street': 8995, 'steal': 5499, 'atl': 3799},
    "Structure": {'mrp': 11495, 'street': 8495, 'steal': 5199, 'atl': 3499},
    "Adizero Adios Pro": {'mrp': 24999, 'street': 19999, 'steal': 12999, 'atl': 8999},
    "Adizero Prime X Strung": {'mrp': 27999, 'street': 22999, 'steal': 14999, 'atl': 10999},
    "Adizero Takumi Sen": {'mrp': 17999, 'street': 13999, 'steal': 8499, 'atl': 5499},
    "Adizero Boston": {'mrp': 14999, 'street': 10999, 'steal': 6499, 'atl': 4299},
    "Adizero Adios": {'mrp': 12999, 'street': 9499, 'steal': 5499, 'atl': 3799},
    "Ultraboost Light": {'mrp': 18999, 'street': 13499, 'steal': 7999, 'atl': 5499},
    "Supernova Prima": {'mrp': 15999, 'street': 11999, 'steal': 7200, 'atl': 4999},
    "Adizero SL": {'mrp': 9999, 'street': 6999, 'steal': 3999, 'atl': 2599},
    "Supernova Rise": {'mrp': 12999, 'street': 8999, 'steal': 5200, 'atl': 3499},
    "Metaspeed Sky": {'mrp': 23999, 'street': 19999, 'steal': 13500, 'atl': 9999},
    "Metaspeed Edge": {'mrp': 23999, 'street': 19999, 'steal': 13500, 'atl': 9999},
    "Superblast": {'mrp': 21999, 'street': 21999, 'steal': 15500, 'atl': 12999},
    "Magic Speed": {'mrp': 13999, 'street': 10499, 'steal': 6999, 'atl': 4899},
    "Gel-Nimbus": {'mrp': 16999, 'street': 12499, 'steal': 7500, 'atl': 4999},
    "Gel-Kayano": {'mrp': 16999, 'street': 12999, 'steal': 7999, 'atl': 5499},
    "Novablast": {'mrp': 13999, 'street': 10499, 'steal': 6200, 'atl': 4299},
    "Gel-Cumulus": {'mrp': 12499, 'street': 8999, 'steal': 5499, 'atl': 3699},
    "GT-2000": {'mrp': 11999, 'street': 8499, 'steal': 4999, 'atl': 3499},
    "Fast-R Nitro Elite": {'mrp': 21999, 'street': 16999, 'steal': 10999, 'atl': 7499},
    "Deviate Nitro Elite": {'mrp': 19999, 'street': 14999, 'steal': 9499, 'atl': 6299},
    "Fast-FWD Nitro Elite": {'mrp': 19999, 'street': 13999, 'steal': 8499, 'atl': 5599},
    "Deviate Nitro": {'mrp': 15999, 'street': 11499, 'steal': 6999, 'atl': 4499},
    "MagMax Nitro": {'mrp': 17999, 'street': 13499, 'steal': 8999, 'atl': 5999},
    "ForeverRun Nitro": {'mrp': 13999, 'street': 9999, 'steal': 5999, 'atl': 3899},
    "Magnify Nitro": {'mrp': 13999, 'street': 8999, 'steal': 5499, 'atl': 3499},
    "Velocity Nitro": {'mrp': 10999, 'street': 7499, 'steal': 4499, 'atl': 2899},
    "Liberate Nitro": {'mrp': 8999, 'street': 5999, 'steal': 3599, 'atl': 2299},
    "Endorphin Elite": {'mrp': 29990, 'street': 24999, 'steal': 16999, 'atl': 12999},
    "Endorphin Pro": {'mrp': 23990, 'street': 17990, 'steal': 12499, 'atl': 8999},
    "Endorphin Speed": {'mrp': 18990, 'street': 13990, 'steal': 8999, 'atl': 5999},
    "Kinvara Pro": {'mrp': 17990, 'street': 12490, 'steal': 7999, 'atl': 5299},
    "Triumph": {'mrp': 17999, 'street': 12999, 'steal': 7499, 'atl': 4999},
    "Hurricane": {'mrp': 17990, 'street': 12990, 'steal': 7999, 'atl': 5499},
    "Tempus": {'mrp': 16990, 'street': 11990, 'steal': 7200, 'atl': 4899},
    "Guide": {'mrp': 14990, 'street': 9990, 'steal': 5999, 'atl': 3999},
    "Ride": {'mrp': 14990, 'street': 9990, 'steal': 5999, 'atl': 3899},
    "Kinvara": {'mrp': 13999, 'street': 8999, 'steal': 5499, 'atl': 3499},
    "Rocket X": {'mrp': 24999, 'street': 21999, 'steal': 14999, 'atl': 11499},
    "Cielo X1": {'mrp': 27999, 'street': 24999, 'steal': 16999, 'atl': 12999},
    "Mach X": {'mrp': 19999, 'street': 16499, 'steal': 10999, 'atl': 7999},
    "Carbon X": {'mrp': 18999, 'street': 14999, 'steal': 9499, 'atl': 6999},
    "Bondi": {'mrp': 17999, 'street': 13999, 'steal': 8999, 'atl': 5999},
    "Skyward X": {'mrp': 23999, 'street': 20999, 'steal': 13999, 'atl': 9999},
    "Gaviota": {'mrp': 16999, 'street': 13499, 'steal': 8499, 'atl': 5499},
    "Clifton": {'mrp': 15499, 'street': 12499, 'steal': 7999, 'atl': 5299},
    "Mach": {'mrp': 14999, 'street': 11999, 'steal': 7499, 'atl': 4999},
    "Hyperion Elite": {'mrp': 25999, 'street': 21999, 'steal': 13999, 'atl': 9999},
    "Hyperion Max": {'mrp': 17999, 'street': 14499, 'steal': 8999, 'atl': 6299},
    "Hyperion": {'mrp': 13999, 'street': 10999, 'steal': 6999, 'atl': 4699},
    "Glycerin": {'mrp': 17999, 'street': 13999, 'steal': 8499, 'atl': 5699},
    "Glycerin GTS": {'mrp': 18499, 'street': 14499, 'steal': 8999, 'atl': 5999},
    "Ghost Max": {'mrp': 16999, 'street': 13499, 'steal': 8200, 'atl': 5499},
    "Ghost": {'mrp': 15499, 'street': 11499, 'steal': 6999, 'atl': 4499},
    "Adrenaline GTS": {'mrp': 14999, 'street': 10999, 'steal': 6799, 'atl': 4399},
    "Launch": {'mrp': 10999, 'street': 7999, 'steal': 4999, 'atl': 3299},
    "FuelCell SuperComp Elite": {'mrp': 25999, 'street': 21999, 'steal': 14999, 'atl': 10499},
    "FuelCell SuperComp Trainer": {'mrp': 21999, 'street': 17499, 'steal': 11499, 'atl': 7999},
    "FuelCell SuperComp Pacer": {'mrp': 16999, 'street': 12999, 'steal': 7999, 'atl': 5299},
    "Fresh Foam X 1080": {'mrp': 17999, 'street': 13499, 'steal': 8499, 'atl': 5499},
    "Fresh Foam X More": {'mrp': 16999, 'street': 12499, 'steal': 7999, 'atl': 4999},
    "Fresh Foam X Vongo": {'mrp': 15999, 'street': 11999, 'steal': 7499, 'atl': 4799},
    "FuelCell Rebel": {'mrp': 13999, 'street': 9999, 'steal': 5999, 'atl': 3999},
    "Fresh Foam X 880": {'mrp': 13999, 'street': 9499, 'steal': 5799, 'atl': 3699},
    "FuelCell Propel": {'mrp': 10999, 'street': 7499, 'steal': 4499, 'atl': 2899},
    "Go Run Speed Beast": {'mrp': 22999, 'street': 16999, 'steal': 10999, 'atl': 7499},
    "Go Run Speed Elite Hyper": {'mrp': 18999, 'street': 13999, 'steal': 8499, 'atl': 5699},
    "Go Run Razor": {'mrp': 13499, 'street': 9499, 'steal': 5499, 'atl': 3499},
    "Go Run Razor Excess": {'mrp': 14499, 'street': 9999, 'steal': 5999, 'atl': 3899},
    "Go Run Max Road": {'mrp': 15999, 'street': 11499, 'steal': 6999, 'atl': 4499},
    "Go Run Ride": {'mrp': 14999, 'street': 9999, 'steal': 5999, 'atl': 3799},
    "Go Run Pure": {'mrp': 9999, 'street': 6999, 'steal': 3999, 'atl': 2499},
    "Go Run Persistence": {'mrp': 10999, 'street': 7499, 'steal': 4499, 'atl': 2799},
    "Go Run Consistent": {'mrp': 8499, 'street': 5499, 'steal': 3299, 'atl': 1999},
    "On Cloudboom Echo": {'mrp': 28999, 'street': 24999, 'steal': 16999, 'atl': 12499},
    "On Cloudboom Strike": {'mrp': 29999, 'street': 26999, 'steal': 18499, 'atl': 13999},
    "On Cloudsurfer Next": {'mrp': 19999, 'street': 16999, 'steal': 11499, 'atl': 7999},
    "On Cloudflow": {'mrp': 18999, 'street': 14499, 'steal': 9999, 'atl': 6999},
    "On Cloudmonster": {'mrp': 23499, 'street': 18999, 'steal': 12499, 'atl': 8499},
    "On Cloudmonster Hyper": {'mrp': 24999, 'street': 21999, 'steal': 14999, 'atl': 10499},
    "On Cloudstratus": {'mrp': 21999, 'street': 16499, 'steal': 11200, 'atl': 7499},
    "On Cloudsurfer": {'mrp': 21499, 'street': 17499, 'steal': 11800, 'atl': 7999},
    "On Cloudrunner": {'mrp': 17999, 'street': 14499, 'steal': 9499, 'atl': 6499},
    "Floatride Energy X": {'mrp': 14999, 'street': 10000, 'steal': 6000, 'atl': 4500},
    "Floatride Energy Symmetros": {'mrp': 10999, 'street': 7500, 'steal': 4500, 'atl': 3500},
    "Floatride Energy": {'mrp': 8999, 'street': 7000, 'steal': 4500, 'atl': 3500},
}

SNEAKER_STEAL_THRESHOLDS = {
    # Adidas Originals
    "SL 72": {"mrp": 9999, "street": 6999, "steal": 3500, "atl": 2752},
    "Samba": {"mrp": 10999, "street": 8999, "steal": 4500, "atl": 3799},
    "Gazelle": {"mrp": 9999, "street": 7999, "steal": 3999, "atl": 3299},
    "Handball Spezial": {"mrp": 10999, "street": 8499, "steal": 4499, "atl": 3599},
    "Stan Smith": {"mrp": 8999, "street": 5999, "steal": 3200, "atl": 2499},
    "Superstar": {"mrp": 8999, "street": 5999, "steal": 3200, "atl": 2499},
    "Campus 00s": {"mrp": 9999, "street": 6999, "steal": 3600, "atl": 2899},
    "Forum Low": {"mrp": 9999, "street": 6499, "steal": 3400, "atl": 2699},

    # Nike Sportswear & Heritage
    "P-6000": {"mrp": 8995, "street": 6495, "steal": 3500, "atl": 2895},
    "Dunk Low": {"mrp": 8695, "street": 7495, "steal": 4500, "atl": 3699},
    "Air Force 1 '07": {"mrp": 9695, "street": 7995, "steal": 4400, "atl": 3495},
    "Cortez": {"mrp": 7495, "street": 5495, "steal": 2999, "atl": 2495},
    "Killshot 2": {"mrp": 7995, "street": 5995, "steal": 3400, "atl": 2795},
    "Vomero 5": {"mrp": 14995, "street": 11495, "steal": 6499, "atl": 4995},
    "Air Max 1": {"mrp": 12795, "street": 9495, "steal": 5200, "atl": 3995},
    "Air Max 90": {"mrp": 11895, "street": 8995, "steal": 4999, "atl": 3795},
    "V2K Run": {"mrp": 10795, "street": 8495, "steal": 4800, "atl": 3695},
    "Initiator": {"mrp": 5495, "street": 3995, "steal": 2499, "atl": 1995},

    # Asics Sportstyle
    "Gel-1130": {"mrp": 8999, "street": 6999, "steal": 3800, "atl": 3199},
    "Gel-Kayano 14": {"mrp": 13999, "street": 10999, "steal": 6500, "atl": 4999},
    "Gel-NYC": {"mrp": 12999, "street": 9999, "steal": 5900, "atl": 4499},
    "GT-2160": {"mrp": 10999, "street": 8499, "steal": 4800, "atl": 3699},
    "Japan S": {"mrp": 6999, "street": 4999, "steal": 2800, "atl": 2199},
    "EX89": {"mrp": 8999, "street": 6499, "steal": 3500, "atl": 2699},

    # Puma Sportstyle
    "Palermo": {"mrp": 6999, "street": 4999, "steal": 2800, "atl": 2299},
    "Suede Classic": {"mrp": 6999, "street": 4499, "steal": 2600, "atl": 1999},
    "Clyde": {"mrp": 7999, "street": 5499, "steal": 3000, "atl": 2399},
    "Army Trainer": {"mrp": 7499, "street": 5199, "steal": 2900, "atl": 2299},
    "Easy Rider": {"mrp": 6999, "street": 4799, "steal": 2700, "atl": 2199},

    # New Balance Heritage
    "New Balance 550": {"mrp": 10999, "street": 7999, "steal": 4200, "atl": 3499},
    "New Balance 574": {"mrp": 8999, "street": 5999, "steal": 3200, "atl": 2499},
    "New Balance 1906R": {"mrp": 14999, "street": 11999, "steal": 6800, "atl": 5299},
    "New Balance 2002R": {"mrp": 13999, "street": 10999, "steal": 6200, "atl": 4799},
    "New Balance 530": {"mrp": 9999, "street": 7499, "steal": 3999, "atl": 3199},
    "New Balance 327": {"mrp": 9999, "street": 6999, "steal": 3600, "atl": 2799},
    "New Balance 9060": {"mrp": 15999, "street": 12999, "steal": 7500, "atl": 5999},
    "New Balance 990": {"mrp": 23999, "street": 19999, "steal": 11999, "atl": 8999},
}

STEAL_THRESHOLDS.update(SNEAKER_STEAL_THRESHOLDS)

